# ═══════════════════════════════════════════════════════════════════════════════
# TESTES UNITÁRIOS - G-CODE GENERATOR
# ═══════════════════════════════════════════════════════════════════════════════
"""
Testes unitários para geração de G-code CNC plasma.
"""
import pytest
from unittest.mock import patch, MagicMock
import sys
import re
from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent.parent
sys.path.insert(0, str(ROOT_DIR))


class TestGCodeCommands:
    """Testes de comandos G-code básicos."""
    
    def test_g0_rapid_move(self):
        """G0 - Movimento rápido."""
        x, y = 100.5, 200.3
        gcode = f"G0 X{x:.3f} Y{y:.3f}"
        
        assert "G0" in gcode
        assert "X100.500" in gcode
        assert "Y200.300" in gcode
    
    def test_g1_linear_move(self):
        """G1 - Movimento linear com feed."""
        x, y, feed = 150.0, 250.0, 2500
        gcode = f"G1 X{x:.3f} Y{y:.3f} F{feed}"
        
        assert "G1" in gcode
        assert f"F{feed}" in gcode
    
    def test_g2_arc_cw(self):
        """G2 - Arco horário."""
        x, y, i, j = 100, 100, 50, 0
        gcode = f"G2 X{x} Y{y} I{i} J{j}"
        
        assert "G2" in gcode
        assert f"I{i}" in gcode
        assert f"J{j}" in gcode
    
    def test_g3_arc_ccw(self):
        """G3 - Arco anti-horário."""
        x, y, i, j = 100, 100, 0, 50
        gcode = f"G3 X{x} Y{y} I{i} J{j}"
        
        assert "G3" in gcode
    
    def test_m_codes_plasma(self):
        """M-codes para plasma."""
        m_codes = {
            "M3": "Ligar tocha",
            "M5": "Desligar tocha",
            "M7": "Mist coolant ON",
            "M8": "Flood coolant ON",
            "M9": "Coolant OFF",
        }
        
        for code, desc in m_codes.items():
            assert code.startswith("M")
            assert int(code[1:]) >= 0


class TestGCodeGeneration:
    """Testes de geração de G-code completo."""
    
    def test_header_generation(self):
        """Gerar header do G-code."""
        header = """
; Generated by Engenharia CAD - CNC Plasma
; Date: 2026-04-06
; Material: Mild Steel
; Thickness: 6.0mm
G21 ; Metric units
G90 ; Absolute positioning
G40 ; Cancel cutter compensation
        """.strip()
        
        assert "G21" in header  # Métrico
        assert "G90" in header  # Absoluto
        assert "Generated by" in header
    
    def test_pierce_sequence(self):
        """Sequência de pierce (perfuração)."""
        pierce_height = 3.8
        pierce_delay = 500
        
        pierce_code = f"""
G0 Z{pierce_height:.1f} ; Pierce height
M3 ; Torch ON
G4 P{pierce_delay/1000:.1f} ; Pierce delay
        """.strip()
        
        assert f"Z{pierce_height:.1f}" in pierce_code
        assert "M3" in pierce_code
        assert "G4" in pierce_code
    
    def test_cut_sequence(self):
        """Sequência de corte."""
        cut_height = 1.5
        feed = 2500
        
        cut_code = f"""
G1 Z{cut_height:.1f} F500 ; Cut height
G1 X100.000 Y0.000 F{feed} ; Cut
        """.strip()
        
        assert f"Z{cut_height:.1f}" in cut_code
        assert f"F{feed}" in cut_code
    
    def test_lead_in_arc(self):
        """Lead-in em arco."""
        radius = 5.0
        # Lead-in em arco para entrada suave
        lead_in = f"G2 X0.000 Y0.000 I{radius:.3f} J0.000"
        
        assert "G2" in lead_in
        assert f"I{radius:.3f}" in lead_in
    
    def test_lead_out_arc(self):
        """Lead-out em arco."""
        radius = 3.0
        lead_out = f"G2 X{radius:.3f} Y0.000 I0.000 J{radius:.3f}"
        
        assert "G2" in lead_out
    
    def test_footer_generation(self):
        """Gerar footer do G-code."""
        footer = """
M5 ; Torch OFF
G0 Z25.0 ; Safe height
G0 X0 Y0 ; Return home
M30 ; Program end
        """.strip()
        
        assert "M5" in footer
        assert "M30" in footer


class TestGCodeValidation:
    """Testes de validação de G-code."""
    
    def test_valid_gcode_line(self):
        """Validar linha de G-code."""
        pattern = r"^[GM]\d+(\s+[XYZIJKFSP][\d\-\.]+)*(\s*;.*)?$"
        
        valid_lines = [
            "G0 X100.000 Y200.000",
            "G1 X50.5 Y75.3 F2500",
            "M3 ; Torch ON",
            "G2 X0 Y0 I50 J0",
        ]
        
        for line in valid_lines:
            # Simplificado - em produção usaria regex mais completo
            assert line[0] in "GM"
    
    def test_invalid_coordinates(self):
        """Detectar coordenadas inválidas."""
        max_coord = 10000  # mm
        
        invalid_coords = [
            {"x": 15000, "y": 0},     # X fora do limite
            {"x": 0, "y": -15000},    # Y negativo excessivo (> max_coord)
        ]
        
        for coord in invalid_coords:
            x_valid = abs(coord["x"]) <= max_coord
            y_valid = abs(coord["y"]) <= max_coord
            
            # Both coords must be invalid (at least one is out of bounds)
            assert not (x_valid and y_valid)
    
    def test_feed_rate_limits(self):
        """Verificar limites de feed rate."""
        min_feed = 100   # mm/min
        max_feed = 15000 # mm/min
        
        test_feeds = [50, 500, 2500, 20000]
        
        for feed in test_feeds:
            valid = min_feed <= feed <= max_feed
            if feed == 50 or feed == 20000:
                assert valid is False
            else:
                assert valid is True


class TestGCodePostProcessor:
    """Testes do post-processor."""
    
    def test_hypertherm_format(self):
        """Formato Hypertherm."""
        # Hypertherm usa comandos específicos
        hypertherm_codes = {
            "torch_on": "M3",
            "torch_off": "M5",
            "thc_enable": "M10",
            "thc_disable": "M11",
        }
        
        assert hypertherm_codes["torch_on"] == "M3"
    
    def test_fanuc_format(self):
        """Formato Fanuc."""
        fanuc_codes = {
            "spindle_on": "M3",
            "spindle_off": "M5",
            "coolant_on": "M8",
            "coolant_off": "M9",
        }
        
        assert fanuc_codes["coolant_on"] == "M8"
    
    def test_mach3_format(self):
        """Formato Mach3."""
        mach3_header = "(Mach3 G-Code)\n(Units: MM)\nG21\nG90\nG17"
        
        assert "Mach3" in mach3_header
        assert "G21" in mach3_header


class TestGCodeOptimization:
    """Testes de otimização de G-code."""
    
    def test_remove_redundant_moves(self):
        """Remover movimentos redundantes."""
        gcode_lines = [
            "G0 X0 Y0",
            "G0 X0 Y0",  # Redundante
            "G0 X100 Y0",
            "G0 X100 Y0",  # Redundante
        ]
        
        optimized = []
        last_pos = None
        
        for line in gcode_lines:
            if line != last_pos:
                optimized.append(line)
                last_pos = line
        
        assert len(optimized) == 2
    
    def test_optimize_rapid_sequence(self):
        """Otimizar sequência de rapids."""
        # Combinar rapids consecutivos
        rapids = [
            "G0 X100",
            "G0 Y100",
        ]
        
        combined = "G0 X100 Y100"
        
        # Em produção, optimizer combinaria as linhas
        assert "X100" in combined and "Y100" in combined
    
    def test_minimize_air_cuts(self):
        """Minimizar cortes em ar (rapids)."""
        total_rapid_distance = 500  # mm
        total_cut_distance = 2000   # mm
        
        rapid_ratio = total_rapid_distance / (total_rapid_distance + total_cut_distance)
        
        # Boa otimização = rapid ratio < 25%
        assert rapid_ratio < 0.25


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
